# Generated by Django 6.0.4 on 2026-05-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_walkin_promotion_minvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='home_visit',
            field=models.BooleanField(default=False),
        ),
    ]
