# Generated by Django 6.0.4 on 2026-05-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_home_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='home_visit_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
