# Generated by Django 6.0.4 on 2026-05-15 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0011_add_cosmetics_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free_trial', 'Free Trial'), ('starter', 'Starter'), ('professional', 'Professional'), ('premium', 'Premium')], default='free_trial', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('billing_name', models.CharField(blank=True, max_length=255)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transaction_ref', models.CharField(blank=True, max_length=100)),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='salons.salon')),
            ],
        ),
    ]
