# Generated by Django 6.0.4 on 2026-05-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_is_private_service_owner_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonservice',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salonservice',
            name='is_price_starting_from',
            field=models.BooleanField(default=False),
        ),
    ]
