# Generated by Django 6.0.4 on 2026-05-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_price_starting_from_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonservice',
            name='home_visit_available',
            field=models.BooleanField(default=False),
        ),
    ]
