# Generated by Django 6.0.4 on 2026-05-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_hv_available_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Hair', 'Hair'), ('Nails', 'Nails'), ('Skin', 'Skin'), ('Makeup', 'Makeup'), ('Bridal', 'Bridal & Party')], max_length=20),
        ),
    ]
