# Generated by Django 6.0.4 on 2026-06-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_add_bridal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonservice',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
