# Generated by Django 6.0.4 on 2026-07-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_salonservice_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
