# Generated by Django 6.0.4 on 2026-06-05 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_cosmeticorder_cosmeticorderitem_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='valuation_method',
            field=models.CharField(choices=[('FIFO', 'FIFO — First In, First Out'), ('LIFO', 'LIFO — Last In, First Out'), ('FEFO', 'FEFO — First Expired, First Out')], default='FIFO', max_length=4),
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=80)),
                ('quantity_received', models.PositiveIntegerField()),
                ('quantity_remaining', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='inventory.grn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product')),
            ],
            options={
                'ordering': ['received_date', 'created_at'],
            },
        ),
    ]
