# Generated by Django 6.0.4 on 2026-06-12 08:57

import utils.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_valuation_method_and_product_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmeticorder',
            name='client_name',
            field=utils.encryption.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='cosmeticorder',
            name='client_phone',
            field=utils.encryption.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cosmeticorder',
            name='delivery_address',
            field=utils.encryption.EncryptedTextField(blank=True, default=''),
        ),
    ]
