# Generated by Django 6.0.4 on 2026-06-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payhere_merchant_id', models.CharField(blank=True, default='', max_length=100)),
                ('payhere_merchant_secret', models.CharField(blank=True, default='', max_length=255)),
                ('payhere_sandbox', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
            },
        ),
    ]
