# Generated by Django 6.0.4 on 2026-06-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='notification_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='notification_email_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='notification_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
