# Generated by Django 6.0.4 on 2026-05-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_add_bridal_category'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='home_visit_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='staff_member_specialties', to='services.service'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='working_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
