# Generated by Django 6.0.4 on 2026-06-12 08:57

import utils.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_encrypt_pii'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffmember',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='full_name',
            field=utils.encryption.EncryptedTextField(),
        ),
    ]
