# Generated by Django 6.0.4 on 2026-07-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_encrypt_pii_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
