# Generated by Django 6.0.4 on 2026-05-04 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'salon_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='salons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saloncalendar',
            name='salon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='salons.salon'),
        ),
    ]
