# Generated by Django 6.0.4 on 2026-05-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0005_salonstaff_working_days_specialties'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
