# Generated by Django 6.0.4 on 2026-05-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0007_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='home_visit_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
