# Generated by Django 6.0.4 on 2026-05-13 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0008_home_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonstaff',
            name='home_visit_available',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SalonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='salon_images/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='salons.salon')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
