# Generated by Django 6.0.4 on 2026-05-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0009_hv_available_staff_salon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='salon_logos/'),
        ),
    ]
