# Generated by Django 6.0.4 on 2026-05-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0010_add_logo_to_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='cosmetics_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
