# Generated by Django 6.0.4 on 2026-05-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0012_add_color_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='gender_focus',
            field=models.CharField(choices=[('unisex', 'Unisex'), ('male', 'Male (Barbershop)'), ('female', 'Female (Ladies Salon)')], default='unisex', max_length=10),
        ),
        migrations.AddField(
            model_name='salon',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
