# Generated by Django 6.0.4 on 2026-05-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0013_add_location_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='salon_covers/'),
        ),
    ]
