# Generated by Django 6.0.4 on 2026-06-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0016_revert_contact_number_encryption'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='facilities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
