# Generated by Django 6.0.4 on 2026-06-12 08:57

import utils.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0017_add_facilities_to_salon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonstaff',
            name='full_name',
            field=utils.encryption.EncryptedTextField(),
        ),
    ]
