# Generated by Django 6.0.4 on 2026-06-24 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0018_encrypt_pii_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosmeticsGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='cosmetics_gallery/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosmetics_gallery', to='salons.salon')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
