# Generated by Django 6.0.4 on 2026-07-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0019_add_cosmetics_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='custom_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('discount', 'Discount'), ('custom', 'Custom Deal')], default='discount', max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
