# Generated by Django 6.0.4 on 2026-05-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Admin'), ('salon_owner', 'Salon Owner'), ('client', 'Client'), ('employee', 'Employee')], default='client', max_length=20),
        ),
    ]
